server:
  port: 8101

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://auth-service/api/v1/auth/.well-known/jwks.json

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

qticket:
  auth:
    allowed-service-names-for-account-creation:
      - "auth-service"

