package de.qf0xb.qticket.auth.service.jpa;

import de.qf0xb.qticket.auth.model.rbac.RoleEntity;
import de.qf0xb.qticket.auth.repository.RoleEntityRepository;
import de.qf0xb.qticket.auth.service.RoleService;
import de.qf0xb.qticket.problem.exceptions.auth.RoleNotFoundException;
import de.qf0xb.qticket.security.rbac.AppPermission;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

@Slf4j
@Service
public class JpaRoleService extends RoleService {
    private final RoleEntityRepository roleRepository;

    public JpaRoleService(RoleEntityRepository roleEntityRepository) {
        this.roleRepository = roleEntityRepository;
    }

    @Override
    public List<RoleEntity> getAllRoles() {
        return roleRepository.findAll();
    }

    @Override
    public RoleEntity getRoleByName(String name) {
        return roleRepository.findByName(name).orElseThrow(() ->
                new RoleNotFoundException("Role '%s' not found".formatted(name)));
    }

    @Override
    public RoleEntity getRoleById(UUID id) {
        return roleRepository.findById(id).orElseThrow(() ->
                new RoleNotFoundException("Role with id '%s' not found".formatted(id)));
    }

    @Override
    public RoleEntity createRole(String name) {
        RoleEntity role = new RoleEntity();
        role.setName(name);
        return createRole(role);
    }

    @Override
    public RoleEntity createRole(RoleEntity role) {
        if (role == null || role.getName() == null || role.getName().isBlank()) {
            throw new IllegalArgumentException("Role name cannot be null or blank");
        }

        // Make sure no ID is getting set
        // ID's are generated by the database
        role.setId(null);

        // ROLES must be uppercase
        String normalizedName = role.getName().trim().toUpperCase();
        role.setName(normalizedName);

        if(roleRepository.findByName(normalizedName).isPresent()) {
            throw new IllegalArgumentException("Role '%s' already exists".formatted(normalizedName));
        }

        if(role.getParent() != null && roleRepository.findByName(role.getParent().getName()).isEmpty()) {
            throw new IllegalArgumentException("Parent role '%s' does not exist".formatted(role.getParent().getName()));
        }

        if (role.getAppPermission() == null) {
            role.setAppPermission(new LinkedHashSet<>());
        }

        return roleRepository.save(role);
    }

    @Override
    public RoleEntity updateRole(RoleEntity role) {
        if (role == null || role.getId() == null) {
            throw new IllegalArgumentException("Role id must be set");
        }

        RoleEntity existing = getRoleById(role.getId());

        // What can be changed: description, parent
        existing.setDescription(role.getDescription());
        existing.setParent(role.getParent());

        if (role.getName() != null && existing.getName() != role.getName()) {
            throw new IllegalArgumentException("Role name cannot be changed");
        }

        return roleRepository.save(existing);
    }

    private AppPermission parsePermission(String permission) {
        try {
            return AppPermission.valueOf(permission.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid permission: " + permission);
        }
    }

    @Override
    @Transactional
    public RoleEntity addPermissionToRole(String name, String permission) {
        return addPermissionToRole(getRoleByName(name), parsePermission(permission));
    }

    @Override
    @Transactional
    public RoleEntity addPermissionToRole(RoleEntity role, String permission) {
        return addPermissionToRole(role, parsePermission(permission));
    }

    @Override
    @Transactional
    public RoleEntity addPermissionToRole(String name, AppPermission permission) {
        return addPermissionToRole(getRoleByName(name), permission);
    }

    @Override
    @Transactional
    public RoleEntity addPermissionToRole(RoleEntity role, AppPermission permission) {
        RoleEntity existing = getRoleById(role.getId());
        existing.getAppPermission().add(permission);
        return roleRepository.save(existing);
    }

    @Override
    @Transactional(readOnly = true)
    public Set<AppPermission> getPermissionsOfRole(String name) {
        return getPermissionsOfRole(getRoleByName(name));
    }

    @Override
    @Transactional(readOnly = true)
    public Set<AppPermission> getPermissionsOfRole(RoleEntity role) {
        Set<AppPermission> permissions = new LinkedHashSet<>();

        RoleEntity current = getRoleById(role.getId());
        while (current != null) {

            if (current.getAppPermission() != null) {
                permissions.addAll(current.getAppPermission());
            }
            current = current.getParent();
        }

        return permissions;
    }

    @Override
    @Transactional
    public RoleEntity removePermissionFromRole(String name, String permission) {
        return removePermissionFromRole(getRoleByName(name), parsePermission(permission));
    }

    @Override
    @Transactional
    public RoleEntity removePermissionFromRole(RoleEntity role, String permission) {
        return removePermissionFromRole(role, parsePermission(permission));
    }

    @Override
    @Transactional(readOnly = true)
    public RoleEntity removePermissionFromRole(String name, AppPermission permission) {
        return removePermissionFromRole(getRoleByName(name), permission);
    }

    @Override
    @Transactional
    public RoleEntity removePermissionFromRole(RoleEntity role, AppPermission permission) {
        RoleEntity existing = getRoleById(role.getId());
        existing.getAppPermission().remove(permission);
        return roleRepository.save(existing);
    }

    @Override
    public RoleEntity setRoleParent(String name, String parentRoleName) {
        return setRoleParent(getRoleByName(name), getRoleByName(parentRoleName));
    }

    @Override
    public RoleEntity setRoleParent(String name, RoleEntity parentRole) {
        return setRoleParent(getRoleByName(name), parentRole);
    }

    @Override
    public RoleEntity setRoleParent(RoleEntity role, String parentRoleName) {
        return setRoleParent(role, getRoleByName(parentRoleName));
    }

    @Override
    public RoleEntity setRoleParent(RoleEntity role, RoleEntity parentRole) {
        getRoleById(parentRole.getId()); // Check if parent role exists
        RoleEntity existing = getRoleById(role.getId());
        existing.setParent(parentRole);
        return roleRepository.save(existing);
    }

    @Override
    public void deleteRole(String name) {
        deleteRole(getRoleByName(name));
    }

    @Override
    public void deleteRole(RoleEntity role) {
        RoleEntity existing = getRoleById(role.getId());
        roleRepository.delete(existing);
    }

}
