package de.qf0xb.qticket.security.rbac;

public enum AppPermission {
    NONE,
    // USER PERMISSIONS
    OWN_USER_VIEW,
    GLOBAL_USER_VIEW,
    OWN_USER_EDIT_INFO,
    OWN_USER_EDIT_PASSWORD,
    OWN_USER_DELETE,
    USER_CREATE,
    USER_LOCK,
    USER_UNLOCK,
    USER_EDIT,
    USER_SET_ROLE,
    USER_DELETE,
    // ROLE PERMISSIONS
    GLOBAL_ROLE_VIEW,
    ROLE_CREATE,
    ROLE_EDIT,
    ROLE_DELETE,
    // SEARCH PERMISSIONS
    SEARCH_USER,
    SEARCH_USER_ALL,
    SEARCH_USER_BY_USERNAME,
    SEARCH_USER_BY_EMAIL,
    SEARCH_USER_BY_FIRST_NAME,
    SEARCH_USER_BY_LAST_NAME,
    SEARCH_USER_BY_ACTIVE,
    SEARCH_USER_BY_EMAIL_VERIFIED,
    SEARCH_USER_BY_LOCKED
}
